#include <Arduino.h>

#define FEATURE_ENC_A_PIN 4
#define FEATURE_ENC_B_PIN 5
#define FEATURE_ENC_SW_PIN 6
#define KEYBOARD_ENC_A_PIN 7
#define KEYBOARD_ENC_B_PIN 8
#define KEYBOARD_ENC_SW_PIN 9

#define PEDAL_LEFT_PIN A3
#define PEDAL_RIGHT_PIN A2

#define BUTTON_LOGIC 0

#define MAX_NUMB_MODES 10
